export const destinations = [
  {
    id: '1',
    name: 'Neo Tokyo',
    country: 'Japan',
    image: '/placeholder.svg?height=300&width=400',
    price: 2499,
    rating: 4.9,
    duration: '7 days',
    description:
      'Experience the cyberpunk future in the neon-lit streets of Neo Tokyo',
    highlights: ['Shibuya Crossing', 'Robot Restaurant', 'Digital Art Museum'],
  },
  {
    id: '2',
    name: 'Mars Colony Alpha',
    country: 'Mars',
    image: '/placeholder.svg?height=300&width=400',
    price: 15999,
    rating: 4.8,
    duration: '14 days',
    description:
      'Pioneer the ultimate space tourism experience on the Red Planet',
    highlights: ['Olympus Mons', 'Polar Ice Caps', 'Underground Cities'],
  },
  {
    id: '3',
    name: 'Atlantis Resort',
    country: 'Pacific Ocean',
    image: '/placeholder.svg?height=300&width=400',
    price: 4299,
    rating: 4.7,
    duration: '10 days',
    description: 'Dive into luxury at our underwater paradise resort',
    highlights: ['Coral Gardens', 'Submarine Tours', 'Aquatic Spa'],
  },
  {
    id: '4',
    name: 'Sky City',
    country: 'Cloud Nine',
    image: '/placeholder.svg?height=300&width=400',
    price: 3799,
    rating: 4.9,
    duration: '5 days',
    description: 'Float among the clouds in our revolutionary aerial city',
    highlights: ['Cloud Walking', 'Sky Gardens', 'Aurora Views'],
  },
  {
    id: '5',
    name: 'Cyber Singapore',
    country: 'Singapore',
    image: '/placeholder.svg?height=300&width=400',
    price: 1899,
    rating: 4.6,
    duration: '6 days',
    description: 'Explore the smart city of tomorrow with AI-guided tours',
    highlights: ['Gardens by the Bay', 'Marina Bay', 'Sentosa Island'],
  },
  {
    id: '6',
    name: 'Arctic Aurora',
    country: 'Norway',
    image: '/placeholder.svg?height=300&width=400',
    price: 2799,
    rating: 4.8,
    duration: '8 days',
    description: 'Witness the Northern Lights in our luxury ice hotels',
    highlights: ['Northern Lights', 'Ice Hotels', 'Husky Sledding'],
  },
];
